### ISSUE TITLE
Saving, Opening and closing of the 'design/project'

### ISSUE THREAD

**Issue by ponsoc** [totaljs/flowstream#2]
Currently 'design/project' is stored in database.json. 

We would like to be able to choose where to store and how to name this file and on the other hand open this file to start working with it again.

Something like a 'Design' button left of the 'FlowStream' button with a drop down for 'New' and 'Open' would work.

**Comment by petersirka** [comment]
You can rewrite it by your needs, just update `/definitions/flowstream.js`:

- https://github.com/totaljs/flowstream/blob/main/definitions/flowstream.js#L19
- I don't recommend changing `modules/flowstream.js` because the module contains the architecture for the Total.js FlowStream algorithm

The project structure serves as a sample only to modify it by your needs except for the `modules/flowstream.js` file. Therefore is the **FlowStream designer** is provided as an independent app. FlowStream is not an end solution. It's a product prepared for many customizations. Here is another product built on this project: https://github.com/totaljs/tms

**Comment by ponsoc** [comment]
Ty Peter, we will have a look at it. For now I will close the issue.
