### ISSUE TITLE
[Feature] Ability to determine if a connected flow is finished processing message

### ISSUE THREAD

**Issue by alaminopu** [totaljs/flowstream#5]
We want to create a component (Ex. Control component) that has the ability to determine if a connected flow to that component is finished processing all the messages. Which will allow us to trigger another flow based on that. 

Currently it's not possible since it doesn't have any state to determine if it's still processing or not, however, I believe if we add some checking and rules in the engine, it would be possible.

I was thinking a lot about it and come up with the following rules - Take a look at the photo 

<img width="865" alt="Screenshot 2021-08-26 at 3 10 03 PM" src="https://user-images.githubusercontent.com/1296554/130978642-70f95fff-4e4a-413b-a737-c385432ce546.png">

**Comment by petersirka** [comment]
Sorry for delay.

> Currently it's not possible since it doesn't have any state to determine if it's still processing or not, however, I believe if we add some checking and rules in the engine, it would be possible.

Not exactly. You can determine quickly if some component is processing some messages via [`instance.stats`](https://docs.totaljs.com/total4/5aed2001pj51c/#79d32001mc51c). But your "**control component**" will have a lot of work to do because the component will need to check all connections to itself, and then it must check each component's stats (not complicated). Of course, we can help you with it.

**Comment by alaminopu** [comment]
@petersirka  I was able to make it work with the concept you shared using `instance.stats`
