### ISSUE TITLE
[Improvement] Working with configuration variables

### ISSUE THREAD

**Issue by ponsoc** [totaljs/flowstream#7]
Hi Peter,

To make the most use of the global variables for configuration of flows or the project We are thinking about the following improvements on the variable system.

I will use variables2 to as a term to reference the variables you can put in the overview of all flows and variables1 to reference the variables you can put into the flow itself. 

So the idea is that you have the ability to reference to variables2 within variables1. Something like

![image](https://user-images.githubusercontent.com/36486184/131119620-23ca3411-e065-4bb7-955f-e33a771e858a.png)

Also in both variables1 and variables2 it would be great if you can reference an ENV variable. Something like

![image](https://user-images.githubusercontent.com/36486184/131119908-0860c784-0929-4afc-8323-af69a73eb71d.png)

Last but not least you want to be able reference the variables1 and variables2 within the component instance settings. You could currently of course do some parsing within the component but that would mean you have to implement on a per component basis. It would be nice if this becomes part of the engine.

![image](https://user-images.githubusercontent.com/36486184/131120205-b88b1880-bc5d-4cec-9b26-0bdd71063c6d.png)

All and all these improvements would really make the variable system a really powerful configuration feature.

**Comment by petersirka** [comment]
I was thinking about it, and it's not a good idea to implement. However, I don't see any problem using mixed values between `instance.main.variables`, `instance.main.variables2` or `process.env`.

__Example__:

```js
var value = instance.main.variables.KEY || instance.main.variables2.KEY || process.env.KEY;
```
or you can use our predefined formatter [`message.variables(str, [data])`](https://docs.totaljs.com/total4/40844001ni51c/#ac8af001jc51c)

```js
instance.message = function($) {

    // $.variables() replaces all {key} phrases for values from "variables", "variables2" or additional "data"
    var url = $.variables(config.url, process.env);

};
```

### What's the problem with extending local variables by adding string references?

There is a problem with references. `variables` object is used as it is, so right now, it's not possible to keep two instances of `variables` with various values. Then each instance can change variables dynamically, but in this case - the variables will see only real values, not identifiers in the form `$flow.myFlow...`.

---

Therefore, I recommend using **code in the example above**.

**Comment by alaminopu** [comment]
Hi @petersirka, would it be easier if you introduce some templating syntax for variable parsing? Example: `{{instance.main.variables2.apiConfig}}` or `%instance.main.variables2.apiConfig%`. Then whenever some need value from a variable instead of static value, they can use the template syntax. 

What do you think?

**Comment by petersirka** [comment]
Hi @alaminopu.
It's not about the parsing variables.

- I can add a method something like `instance.readvariable(key)`, and this method tries to return a parsed value
- `instance.main.variables.key`, `instance.main.variables2.key` will contain raw values as they are entered in the `Variables` window

But, important: your components should use this new method instead of current usage.

**Comment by alaminopu** [comment]
Hi @petersirka, Just to give you some context. What we end up doing - 

- Use this syntax `%apiConfig%` whenever we need to treat it as variable instead of normal string value
- Parse it using regex and replace variable value (Either from `instance.main.variables` or `instance.main.variables2` or `process.env`. we defined some precedence in order to avoid conflict)

I think we can close this issue now.
